[2022-05-16 17:43:50,394] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: counter.if_not_exists scheduled__2022-05-16T17:42:00+00:00 [queued]>
[2022-05-16 17:43:50,413] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: counter.if_not_exists scheduled__2022-05-16T17:42:00+00:00 [queued]>
[2022-05-16 17:43:50,413] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 17:43:50,414] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-16 17:43:50,414] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 17:43:50,650] {manager.py:50} ERROR - Failed to extract metadata 'NoneType' object has no attribute 'host' task_type=PostgresOperator ***_dag_id=counter task_id=if_not_exists ***_run_id=scheduled__2022-05-16T17:42:00+00:00 
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/manager.py", line 40, in extract_metadata
    task_metadata = extractor.extract()
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/postgres_extractor.py", line 59, in extract
    authority=self._get_authority(),
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/postgres_extractor.py", line 131, in _get_authority
    if self.conn.host and self.conn.port:
AttributeError: 'NoneType' object has no attribute 'host'
[2022-05-16 17:43:51,709] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): if_not_exists> on 2022-05-16 17:42:00+00:00
[2022-05-16 17:43:51,717] {standard_task_runner.py:52} INFO - Started process 83 to run task
[2022-05-16 17:43:51,722] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'counter', 'if_not_exists', 'scheduled__2022-05-16T17:42:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/laendleimmo.py', '--cfg-path', '/tmp/tmpkxxv6_ou', '--error-file', '/tmp/tmpbviugtwp']
[2022-05-16 17:43:51,725] {standard_task_runner.py:80} INFO - Job 10: Subtask if_not_exists
[2022-05-16 17:43:52,281] {task_command.py:369} INFO - Running <TaskInstance: counter.if_not_exists scheduled__2022-05-16T17:42:00+00:00 [running]> on host f61c633188f3
[2022-05-16 17:43:52,594] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=datascience@example.com
AIRFLOW_CTX_DAG_OWNER=datascience
AIRFLOW_CTX_DAG_ID=counter
AIRFLOW_CTX_TASK_ID=if_not_exists
AIRFLOW_CTX_EXECUTION_DATE=2022-05-16T17:42:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-16T17:42:00+00:00
[2022-05-16 17:43:52,640] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `example_db` isn't defined
[2022-05-16 17:43:52,647] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=counter, task_id=if_not_exists, execution_date=20220516T174200, start_date=20220516T174350, end_date=20220516T174352
[2022-05-16 17:43:52,675] {manager.py:50} ERROR - Failed to extract metadata 'NoneType' object has no attribute 'host' task_type=PostgresOperator ***_dag_id=counter task_id=if_not_exists ***_run_id=scheduled__2022-05-16T17:42:00+00:00 
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/manager.py", line 38, in extract_metadata
    task_metadata = extractor.extract_on_complete(task_instance)
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/base.py", line 63, in extract_on_complete
    return self.extract()
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/postgres_extractor.py", line 59, in extract
    authority=self._get_authority(),
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/postgres_extractor.py", line 131, in _get_authority
    if self.conn.host and self.conn.port:
AttributeError: 'NoneType' object has no attribute 'host'
[2022-05-16 17:43:52,766] {standard_task_runner.py:97} ERROR - Failed to execute job 10 for task if_not_exists (The conn_id `example_db` isn't defined; 83)
[2022-05-16 17:43:52,781] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-16 17:43:52,899] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
